pub const MAX_WORKERS: usize = 64;
pub const MAX_QUEENS: usize = 8;

pub const MULTI_EVOLUTION_WORKERS: usize = 64;
pub const DOUBLE_GAS_PER_BASE_WORKERS: usize = 52;
pub const UNLOCK_ROACH_WORKERS: usize = 26;
pub const UNLOCK_HYDRA_WORKERS: usize = 38;
pub const UNLOCK_LATE_TECH_WORKERS: usize = 48;
pub const UNLOCK_REALLY_LATE_TECH_WORKERS: usize = 56;
pub const UNLOCK_OVERSEER_WORKERS: usize = 40;
pub const UNLOCK_BURROW_WORKERS: usize = 25;
pub const OVERLORD_SPEED_WORKERS: usize = 30;
pub const UNLOCK_TUNNELING_CLAWS_WORKERS: usize = 35;

pub const UNLOCK_UPGRADES_WORKERS: usize = 40;
pub const SAVE_FOR_ATTACK_UPGRADES_ON_UNITS: usize = 4;
pub const SAVE_FOR_DEFENSE_UPGRADES_ON_UNITS: usize = 6;

pub const CREEP_DISTANCE_TO_HALL: f32 = 3.5f32;
pub const CREEP_SPREAD_MAP_DISTANCE: usize = 4;
pub const CREEP_SPREAD_DISTANCE: usize = 6;
pub const CREEP_SPREAD_ENERGY: u32 = 55;

pub const TRANSFUSION_MIN_ENERGY: u32 = 50;
pub const TRANSFUSION_MAX_RANGE: f32 = 15f32;
pub const TRANSFUSION_MISSING_HEALTH: u32 = 60;

pub const INJECTION_MAX_LARVA: usize = 30;

pub const BURROW_HEALTH_PERCENTAGE: f32 = 0.58f32;
pub const BURROW_DETECTION_RANGE: f32 = 9f32;
pub const UNBURROW_HEALTH_PERCENTAGE: f32 = 0.95f32;

pub const UNLOCK_UNIT_PRIORITY: usize = 500;

pub const SPECIAL_TECH_UNIT_VALUE: f32 = 1f32;
pub const EARLY_TECH_UNIT_VALUE: f32 = 10f32;
pub const LATE_TECH_UNIT_VALUE: f32 = 15f32;
pub const REALLY_LATE_TECH_UNIT_VALUE: f32 = 20f32;

pub const UPGRADE_UNIT_PRIORITY: f32 = 1f32;

pub const DEFAULT_ARMY_UNIT_PRIORITY: f32 = 35f32;
