pub const MAX_WORKERS: usize = 70;
pub const MAX_QUEENS: usize = 6;
pub const MULTI_EVOLUTION_WORKERS: usize = MAX_WORKERS;
pub const DOUBLE_GAS_PER_BASE_WORKERS: usize = 34;
pub const UNLOCK_ROACH_WORKERS: usize = 26;
pub const UNLOCK_HYDRA_WORKERS: usize = 42;
pub const UNLOCK_LATE_TECH_WORKERS: usize = MAX_WORKERS * 8 / 10;
pub const UNLOCK_REALLY_LATE_TECH_WORKERS: usize = MAX_WORKERS * 9 / 10;
pub const UNLOCK_OVERSEER_WORKERS: isize = 29;
pub const UNLOCK_BURROW_WORKERS: usize = 25;
pub const OVERLORD_SPEED_WORKERS: usize = 30;
pub const UNLOCK_TUNNELING_CLAWS_WORKERS: usize = 35;

pub const UNLOCK_UPGRADES_WORKERS: usize = 45;
pub const SAVE_FOR_ATTACK_UPGRADES_ON_UNITS: usize = 5;
pub const SAVE_FOR_DEFENSE_UPGRADES_ON_UNITS: usize = 10;

pub const CREEP_DISTANCE_TO_HALL: f32 = 3.5f32;
pub const CREEP_SPREAD_MAP_DISTANCE: usize = 4;
pub const CREEP_SPREAD_DISTANCE: usize = 6;
pub const CREEP_SPREAD_ENERGY: u32 = 55;

pub const TRANSFUSION_MIN_ENERGY: u32 = 50;
pub const TRANSFUSION_MAX_RANGE: f32 = 15f32;
pub const TRANSFUSION_MISSING_HEALTH: u32 = 60;

pub const INJECTION_MAX_LARVA: usize = 20;

pub const BURROW_HEALTH_PERCENTAGE: f32 = 0.55f32;
pub const BURROW_DETECTION_RANGE: f32 = 9f32;
pub const UNBURROW_HEALTH_PERCENTAGE: f32 = 0.95f32;
