[package]
name = "caninana-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-sc2 = "1.1"
rand = "0.6"
log = "0.4"
