[package]
name = "caninana-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-sc2 = {version = "1.1", features = ["enemies_cache"] }
rand = "0.8"
log = "0.4"
